import React from "react"

function History() {
    return (
        <div className="p-2 text-center text-2xl text-lg text-gray-700">
            La creación del Gabinete de Arqueología en 1987 se apega al cumplimiento de la normativa internacional para la protección de centros históricos. La Habana Vieja había sido declarada Patrimonio de la Humanidad en 1982, y dicho reconocimiento presupuso la realización de investigaciones arqueológicas previas a las necesarias labores de restauración y rehabilitación del territorio declarado. La sistematicidad que adquiere la disciplina a partir de entonces -en especial la que fue denominada Arqueología Colonial y posteriormente Arqueología Histórica- ofrece un conocimiento sin precedentes. Dicha proyección desde y hacia miradas más integradoras y complejas de la ciudad, sus suelos e inmuebles –entendidos todos como un yacimiento único-, ha enriquecido y transformado, en más de tres décadas de existencia, las visiones academicistas de la historia municipal y provincial.
            La responsabilidad inicial de liderar la institución la tuvo el investigador Leandro Romero Estébanez; desde el año 1993 hasta la fecha ocupa este cargo Roger Arrazcaeta Delgado. En la década de los años 80 los planes de restauración y rehabilitación se emprendieron a partir de una estrategia de concentración de acciones físicas de salvataje en dos de las plazas principales: Plaza de Armas y Plaza de la Catedral, así como en los ejes viales Oficios, Mercaderes, Tacón y Obispo. Fueron restaurados además grandes monumentos, como el Convento de Santa Clara y las fortificaciones Los Tres Reyes del Morro y San Carlos de la Cabaña. Dichos requerimientos restaurativos implicaron el trabajo supeditado de los técnicos a las exigencias establecidas por los planes de restauración de la Oficina, sobre todo durante los años iniciales (1987-1994). Con la nueva década sobrevino un cambio significativo, cuando en los años 90 se decide apostar más al trabajo con la comunidad del centro histórico, verdaderos guardianes y responsables a futuro, del éxito y la continuidad de la labor conservativa que es realizada. Este proceso de humanización y socialización de los enfoques técnicos de conservación y gestión se dio a la par del impulso ofrecido a las investigaciones sociales, históricas y arqueológicas dentro de la red institucional de la Oficina.
            Los nuevos cauces suscitaron variadas inquietudes científicas así como diferentes y novedosas líneas de trabajo e investigación, de las cuales usted podrá informarse en esta página. Las mismas han proporcionado resultados alentadores en cuanto a la integración de los objetivos particulares de investigación del Gabinete, con las directrices generales del trabajo de restauración, rehabilitación y gestión llevada a cabo por la Oficina del Historiador. Se iniciaron y desplegaron pautas para la realización de proyectos multi e interdisciplinarios que han tributado no sólo al perfeccionamiento de las razones sobre las cuales se sostiene la disciplina, sino al propósito actual de la Oficina: apostar al desarrollo sostenible del territorio a partir de la salvaguarda y puesta en valor de su patrimonio histórico cultural.
</div>
    );
}

export default History