import React from "react"

function Team() {
    return (
        <div className="p-2 text-center text-2xl text-lg text-gray-700">
            <text>Roger Arrazcaeta Delgado</text>
            <text>Arqueólogo y museólogo. Es director del Gabinete de Arqueología de la Oficina del Historiador de La Habana desde 1993. Es miembro del Grupo de Arqueología Batabanó desde 1972. Ha llevado a cabo y dirigido investigaciones y excavaciones en sitios arqueológicos de Cuba, Colombia y Venezuela, en los campos de la arqueología histórica, arqueología aborigen, arte rupestre y arqueología subacuática. Se ha especializado en las técnicas de excavación estratigráfica y en cerámica del periodo colonial. Realizó estudios y entrenamientos de arqueología de la arquitectura y excavaciones estratigráficas con el doctor Edward C. Harris en Cuba y el doctor Agustín Azkárate en la Universidad del País Vasco, España.  Ha impartido cursos, conferencias y participado como ponente en eventos científicos en Cuba, Colombia, Venezuela, México, Panamá, y Estados Unidos de América. Ha realizado asesorías científicas a los Gabinetes de Arqueología de Santiago de Cuba, Camagüey, Trinidad y Sancti Spíritus. Tiene publicado libros, artículos especializados y divulgativos sobre arqueología cubana. Es fundador y director editorial de la revista Gabinete de Arqueología desde su creación en 2001. Miembro de la Comisión Nacional de Monumentos y de la Subcomisión de Arqueología de Cuba.</text>
            <text>Beatriz A Rodríguez Basulto</text>
            <text>Lic. en Historia del Arte, MSc en Arqueología (Universidad de La Habana), Doctorante en Arqueología (Universidad de Buenos Aires, Argentina). Especialista en Arqueología Histórica del Gabinete de Arqueología, Oficina del Historiador de La Habana, Cuba. Investigadora Adscripta de la Fundación Félix de Azara, Universidad de Maimonides, C. de Buenos Aires, Argentina.</text>
            <text>Desde el año 1996 forma parte del equipo de trabajo del Gabinete de Arqueología de la Oficina del Historiador de La Habana. Ha participado y dirigido diferentes proyectos de investigación arqueológica en La Habana, en Buenos Aires y en otras provincias argentinas. Como docente ha impartido diversas materias en varios niveles académicos de enseñanza. Entre las asignaturas impartidas destacan Arqueología y Antropología, Gestión Integral del Patrimonio, Metodología de las Ciencias Sociales y Filosofía de las Ciencias. Esta labor la ha desempeñado en niveles terciarios, universitarios y de postgrado tanto en La Habana, Cuba, como en Argentina. En cuanto a investigación se ha especializado en temas Filosofía de la Ciencia y de metodología arqueológica esto comprende también la realización de artículos científicos, un libro y varios capítulos de libros. Es miembro de la Lista de Profesionales de la Arqueología de Cuba y forma parte del Consejo Científico de la revista Gabinete de Arqueología.</text>
            <text>César Alonso Sansón. Especialista en Arqueología Histórica. Sección de Arqueología Submarina.</text>
            <text>Graduado en la especialidad de Diseño Industrial. Entre 1992 y 2014 se desempeña como investigador y técnico en arqueología subacuática en las empresas Carisub S.A. y Sermar S.A. participando en las campañas arqueológicas como buzo especialista. Como técnico en arqueología estudia y cataloga las piezas y artefactos de los pecios coloniales, realizando levantamientos, informes y monografías relacionadas. Como investigador consulta los fondos históricos de los archivos cubanos (nacionales y provinciales) como parte de los proyectos de investigación que se derivan de los estudios concretos de cada pecio excavado y la historia marítima naval de Cuba. Participa en el equipo de investigación de los proyectos vinculados a los Programas Nacionales de Ciencia y Técnica de Historia y Ciencias Sociales, específicamente “Pecios de la etapa de los descubrimientos y conquista del Nuevo Mundo”, cuyo resultado queda plasmado en una obra monográfica de historia naval del siglo XVI (inédito). Participa en cursos de capacitación impartidos por la Oficina Regional de la UNESCO y el ARNAC. Colaboró en los trabajos arqueológicos realizados por el Instituto Europeo de Arqueología Submarina en aguas cubanas. En 2014 comienza a trabajar en el Gabinete de Arqueología de la Oficina del Historiador como especialista en Arqueología Histórica en la sección de arqueología subacuática. Participa en las excavaciones que se realizan intramuros de la Habana y como buzo en los pecios del litoral norte de la provincia. Continúa su labor como investigador colaborando en el proyecto de la Ruta del Esclavo del Smithsonian relacionado con los buques negreros y la trata. Apoya los trabajos de instituciones similares de Trinidad y Sancti Spíritus. Ha publicado artículos en la Revista del Gabinete de Arqueología.</text>
            <text>Lisette Roura Alvarez</text>
            <text>Graduada de Arqueología en la Escuela Taller de La Habana Gaspar Melchor de Jovellanos, Licenciada en Estudios Socioculturales, Diplomada en Antropología y Patrimonio, y Doctorada en Ciencias Históricas, se desempeña como Especialista Principal en Arqueología Histórica del Gabinete de Arqueología de la Oficina del Historiador de La Habana, y como profesora de la Universidad de La Habana. Es la autora principal de dos monografías y de una treintena de artículos en el ámbito nacional e internacional. Numerosos centros especializados cubanos han constituido sedes de sus actividades docentes, impartiendo clases, charlas, conferencias y cursos. Ha definido la Arqueología Industrial y la Interacción Indohispánica en La Habana como líneas fundamentales de trabajo, dirigiendo proyectos relacionados con estos temas. Es miembro de la Lista de Profesionales de la Arqueología de Cuba, la Unión de Historiadores de Cuba y forma parte del Consejo Científico de la revista Gabinete de Arqueología.</text>
            <text>Karen Mahé Lugo Romera</text>
            <text>Graduada en la especialidad de Arqueología en la Escuela Taller de La Habana Gaspar Melchor de Jovellanos, Licenciada en Historia en la Universidad de La Habana, Diplomada en Antropología Cultural y  Máster en Ciencias Arqueológicas en la Universidad Complutense de Madrid. Labora como Especialista en Arqueología Histórica en el Gabinete de Arqueología de la Oficina del Historiador de La Habana. Ha participado en numerosas intervenciones en contextos arqueológicos diversos del Centro Histórico de La Habana Vieja; e integrado equipos de trabajo en proyectos nacionales e internacionales.  Entre las líneas de temáticas que ha investigado se encuentra el estudio de las migraciones maya-yucatecas a la isla, la historia de la Arqueología y, actualmente, la participación de la Arqueología en las narrativas nacionales posteriores a 1961 en los manuales para la enseñanza de la Historia en la educación primaria y secundaria. Es miembro de la Lista de Profesionales de la Arqueología de Cuba y forma parte del Consejo Científico de la revista Gabinete de Arqueología.</text>
            <text>Osvaldo Jiménez Vázquez</text>
            <text>Graduado de Nivel Medio Superior. Ingresa en la Sociedad Espeleológica de Cuba en 1986, iniciándose en la arqueología precolombina y la paleontología de vertebrados del Cuaternario. Entre 1995 y 2004 trabajó en el Instituto de Ecología y Sistemática (CITMA). En 2004 pasa al Gabinete de Arqueología de la Oficina del Historiador de La Habana. Durante más de veinte años ha participado en expediciones por el territorio nacional. Participó en el hallazgo de cuatro especies fósiles de mamíferos nuevas para la ciencia: Paralouatta marianae (Primates), Zazamys veronicae (Rodentia), Bubo osvaldoi (Strigidae) y el ofidio viviente Tropidophis spiritus. Es colaborador del grupo de Geología y Paleontología del Museo Nacional de Historia Natural de Cuba y ha colaborado con el Museo Americano de Historia Natural. Ha participado en más de 50 cursos, seminarios, conferencias, entrenamientos y eventos nacionales e internacionales. Tiene 40 publicaciones en revistas nacionales e internacionales. Es miembro de la Sociedad Espeleológica de Cuba, Sociedad Cubana de Zoología, Sociedad Mexicana de Mastozoología y del Grupo de Trabajo de Zooarqueología y Tafonomía Neotropicales del Internacional Council for Archaeozoology.</text>
            <text>Rebeca T. Ortiz Linsuaín</text>
            <text>Licenciada en Historia del Arte. Trabajó en el Museo Numismático como especialista en monedas hispanoamericanas. Desde hace veinte años es miembro del Gabinete de Arqueología de la Oficina del Historiador de La Habana, donde se desempeña en la documentación archivística de los inmuebles que se intervienen arqueológicamente. Ha realizado el análisis de monedas de la época colonial halladas en La Habana Vieja y ha colaborado en la identificación de estas en sitios arqueológicos de Cartagena de Indias, Colombia y Panamá Viejo, Panamá. Sus investigaciones han sido publicadas en la revista especializada Gabinete de Arqueología. Además, ha contribuido con reseñas históricas de inmuebles habaneros en los tres tomos de la obra Para No Olvidar, del doctor Eusebio Leal Spengler.</text>
            <text>Rosalía Oliva Suárez</text>
            <text>Graduada en 1999 en Licenciatura en Historia, Universidad de la Habana. Doctora en Gestión y Preservación del Patrimonio en el 2014, en la Universidad de Granada, España; se ha especializado en historia social, enfatizando en las relaciones entre el urbanismo y la arquitectura con el desarrollo de la sociedad en el período colonial cubano. Ha trabajado como investigadora histórica, desde 1999, en el Gabinete de Arqueología, donde actualmente labora. Profesora en el Colegio Universitario San Gerónimo de La Habana. Desde el 2002 ha publicado artículos relacionado con sus investigaciones, en la revista Gabinete de Arqueología de la OHC, El Castillo de San Salvador de la Punta (2002); Más allá que un Hotel (2007), La arquitectura doméstica habanera del siglo XVII (2015); Los Espacios domésticos habaneros (2016). En el Boletín del Archivo Nacional de la República de Cuba, La población habanera en la segunda mitad del siglo XVII. Los oficios (2013) y en conjunto con la arqueóloga Lisette Roura Álvarez, Historia y Arqueología en el cafetal San Pedro, Sierra del Rosario, Artemisa (2014). Miembro de la Asociación Nacional de Historiadores de Cuba y del ICOM.</text>
            <text>Sonia Menéndez Castro</text>
            <text>Graduada de Arqueología en la Escuela Taller de La Habana Gaspar Melchor de Jovellanos; Licenciada en Historia, en la Universidad de La Habana; Diplomada en Antropología Cultural, Máster en Arqueología, en la Universidad Complutense de Madrid. Es Especialista en Arqueología Histórica del Gabinete de Arqueología de la Oficina del Historiador de La Habana. Sus líneas investigativas abordan los contextos arqueológicos doméstico, funerario, defensivo e industrial. Ha colaborado con diferentes centros investigativos de Cuba, y con las Oficinas del Conservador de Trinidad, Camagüey y Santiago de Cuba. Ha participado en proyectos internacionales de Investigación y Desarrollo, y cuenta con varias publicaciones en ámbito nacional e internacional, que comprenden artículos, capítulos de libros y un libro. Es coordinadora general del equipo para la gestión del Patrimonio Arqueológico en el Centro Histórico de La Habana, y trabaja en el desarrollo de un modelo de Arqueología Preventiva para la gestión del patrimonio arqueológico en la ciudad. Es miembro de la Lista de Profesionales de la Arqueología de Cuba y forma parte del Consejo Científico de la revista Gabinete de Arqueología.</text>
            <text> Yoser Martínez Hernández</text>
            <text>Técnico en Arqueología Histórica, en la Escuela taller Gaspar Melchor de Jovellanos, y Lic. en Preservación y Gestión del Patrimonio Histórico Cultural, en la especialidad de Gestión Sociocultural (2016), en el Colegio Universitario San Gerónimo de La Habana. Se tituló de Diplomado en Antropología en el Instituto Cubano de Antropología, y cursa en la actualidad el Master Oficial en Arqueología Naútica y Subacuática, Universidad de Cádiz, Andalucía, España.</text>
            <text>Especialista en Arqueología Histórica del Gabinete de Arqueología, Oficina del Historiador de La Habana, Cuba, desde 2008. Forma parte del Departamento de Arqueología Subacuática de la institución. Ha participado en diferentes proyectos de investigación arqueológica en La Habana, y otras provincias cubanas, tanto en el ámbito terrestre como marítimo. Ha impartido durante 7 años el Taller para Adolescentes “En Busca del Pasado”, con diversas temáticas relacionadas con la disciplina.  En cuanto a investigación se ha especializado en temas de Arqueología Subacuática,  esto comprende también la realización de variados artículos científicos. Es miembro de la Lista de Profesionales de la Arqueología de Cuba.</text>
            <text>Eduardo Martell Ruiz.</text>
            <text>Especialista en Arqueología Histórica. Lic. En Preservación y Gestión del Patrimonio Histórico Cultural. Labora desde hace 18 años en el Gabinete de Arqueología de la Oficina del Historiador de La Habana. Ha publicado artículos, vinculados con su especialidad en Cuba y en el extranjero. Ha participado en múltiples excavaciones arqueológicas como la Iglesia de San Felipe Neri, en la Casa del Conde de Cañongo y en la Iglesia de la Tercera Orden de San Francisco de Asís. Labora hace un quinquenio en las investigaciones arqueológicas del Convento de Santa Clara de Asís, futura sede del Colegio Santa Clara para la restauración en las Artes y los Oficios. Trabaja en un proyecto de investigación con el Grupo Habana Casabe para la conservación, preservación y gestión de ese alimento milenario y místico que es el casabe.</text>
            <text> Marcos Antonio Acosta Mauri</text>
            <text>Graduado como técnico en Ciencias Informáticas en 2005, actualmente cursa estudios superiores en la carrera de Licenciatura en Gestión y Preservación del Patrimonio Histórico Cultural, en el Colegio Universitario San Gerónimo de La Habana (Facultad extra campus de la Universidad de La Habana). Comienza a trabajar en el Gabinete de Arqueología de la Oficina del Historiador de La Habana en Junio de 2016, donde ha participado en diversas campañas de intervención arqueológica, complementado su superación profesional.</text>
            <text>Ha participado en proyectos  internacionales como "First Coast Maritime Archaeological Project 2017 Field Season" en FL., EE.UU., intervención arqueológica del pecio “Aniversario” en colaboración con Saint Augustine Ligthouse, St. Augustine FL, EE. UU y Estudio Histórico-Arqueológico del Cafetal-Ingenio Angerona” en Artemisa, Cuba desarrollado por la Universidad de Saint Mary, Halifax, Canadá, el Consejo Nacional de Patrimonio Cultural, Cuba, y el  Gabinete de Arqueología de la  Oficina del Historiador de la Ciudad de La Habana .</text>
            <text>Arlene Cordero Alfonso</text>
            <text>Licenciada en Preservación y Gestión del Patrimonio Histórico Cultural, en la Especialidad de Arqueología, en el Colegio Universitario San Gerónimo de La Habana (2017). Ejerce como Especialista en Arqueología Histórica en el Gabinete de Arqueología de la Oficina del Historiador de La Habana, desde 2018. Ha participado en diversas campañas de intervención arqueológica en La Habana y otras provincias, relacionadas con la Arqueología Histórica y aborigen.</text>
            <text>Isabel Rodríguez Blanco</text>
            <text>Técnico en Arqueología Histórica, en la Escuela taller Gaspar Melchor de Jovellanos. Actualmente cursa estudios superiores en la carrera de Licenciatura en Gestión y Preservación del Patrimonio Histórico Cultural, en el Colegio Universitario San Gerónimo de La Habana. Comienza a trabajar en el Gabinete de Arqueología de la Oficina del Historiador de La Habana en Junio de 2018, como técnico en Arqueología Histórica. En la institución ha participado en diversas campañas de intervención arqueológica, en La Habana y otras provincias.</text>
            <text>Susel Jiménez Verdecia</text>
            <text>Graduado de técnico en Ciencias Informáticas en 2010, actualmente cursa estudios superiores en la carrera de Licenciatura en Gestión y Preservación del Patrimonio Histórico Cultural, en el Colegio Universitario San Gerónimo de La Habana. Comienza a trabajar en el Gabinete de Arqueología de la Oficina del Historiador de La Habana en Junio de 2018, como técnico en Arqueología Histórica.</text>
            <text>En la institución ha participado en diversas campañas de intervención arqueológica, en La Habana y otras provincias. Ha participado en proyectos  internacionales como Estudio Histórico-Arqueológico del Cafetal-Ingenio Angerona” en Artemisa, Cuba desarrollado por la Universidad de Saint Mary, Halifax, Canadá, el Consejo Nacional de Patrimonio Cultural, Cuba, y el  Gabinete de Arqueología de la  Oficina del Historiador de la Ciudad de La Habana. .</text>
            <text>Raúl Mesa Morales</text>
            <text>Lic. en Lengua Inglesa de la Facultad de Lenguas Extranjeras de la Universidad de la Habana.</text>
            <text>Desde el año 2005 forma parte del equipo de trabajo del Gabinete de Arqueología de la Oficina del Historiador de La Habana, donde se ha encargado de la traducción a ambos idiomas de la literatura científico-técnica manejada por los especialistas de la institución como parte de los proyectos investigativos y calificación requerida por estos y por especialistas extranjeros colaboradores extranjeros.</text>
            <text>También ha fungido como intérprete para los diversos grupos y colaboradores individuales que han contribuido con el desempeño del trabajo en la sede de la institución o en condiciones de campo.</text>
            <text>Yuri Álvarez Acosta.</text>
            <text>Graduado de Técnico en Ciencias Informáticas. Informático de del Gabinete de Arqueología desde el año 2015.  Ha ejercido prestación de servicios al Palacio de Segundo Cabo desde 2017.</text>
        </div>
    );
}

export default Team